language: python
python: '2.7'
cache: pip

before_install:
  - pip install --upgrade pip
install:
  - pip install codecov
  - pip install -e .[test]
  - pip install flake8
script:
  - pytest --cov
  - flake8 .
after_success:
  - codecov